apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: wasm-caching-poc
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      # Images come from internal OCI registry.
      components:
        - name: http-api
          image: wasmcloud-registry/http-api:v2
        - name: otel
          image: wasmcloud-registry/component:v2
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: test
