apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: otel-component-poc
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      # Images come from internal OCI registry.
      components:
        - name: http-api
          image: wasmcloud-registry:5000/http-api:v13
        - name: otel
          image: wasmcloud-registry:5000/component:v13
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: test
