package dewinz:http-api@0.1.0;

world main {
	import wasi:clocks/wall-clock@0.2.0;
	import wasi:otel/tracing@0.2.0-rc.1;

	import dewinz:component/component@0.1.0;
	import betty-blocks:random-hex/random-hex;

	export wasi:http/incoming-handler@0.2.0;
}
