package dewinz:component@0.1.0;

interface component {
	first: func();

	second: func(something: string);

	third: func() -> result<string, string>;
}

world main {
	import wasi:otel/tracing@0.2.0-rc.1;

	export component;
}
